# Generated by Django 5.1.4 on 2025-10-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrimitra', '0006_comment_parent_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
